import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "@/components/theme/theme-provider";
import { ReduxProvider } from "@/redux/provider";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { Poppins } from "next/font/google";
import { Toaster } from "sonner";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Classkool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <ClerkProvider>
        <GoogleOneTap />
        <body
          className={`${poppins.variable} antialiased dark:bg-gray-950 bg-slate-100 text-gray-950 dark:text-slate-200`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ReduxProvider>{children}</ReduxProvider>
            <Toaster expand />
          </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
